<#
.SYNOPSIS
  Setup vanilla Minecraft server 1.21.10 (SandBox, выживание).
  Downloads server.jar from Mojang.
#>
param(
  [string]$Version = "1.21.10"
)

$ErrorActionPreference = "Stop"

$versionUrls = @{
  "1.21.10" = "https://piston-data.mojang.com/v1/objects/95495a7f485eedd84ce928cef5e223b757d2f764/server.jar"
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path | Out-Null
  }
}

function Write-TextFile([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { Ensure-Dir $dir }
  [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($true)))
}

$root = $PSScriptRoot
$basePort = 25570
$versionDir = Join-Path $root "servers\$Version"
Ensure-Dir $versionDir

$serverJarUrl = $versionUrls["1.21.10"]
$serverJarPath = Join-Path $versionDir "server.jar"

if (-not (Test-Path -LiteralPath $serverJarPath)) {
  Write-Host "Downloading Minecraft 1.21.10 server jar..."
  Invoke-WebRequest -Uri $serverJarUrl -OutFile $serverJarPath -UseBasicParsing
}
else {
  Write-Host "Server jar already present: $serverJarPath"
}

$servers = @(
  @{ Name = "SandBox"; Port = $basePort; Level = "world_sandbox"; Motd = "SandBox (1.21.10) Выживание"; }
)

foreach ($s in $servers) {
  $name = $s.Name
  $dir = Join-Path $versionDir $name
  Ensure-Dir $dir

  # Copy server.jar into each server folder (vanilla uses single jar per dir)
  $jarDest = Join-Path $dir "server.jar"
  if (-not (Test-Path -LiteralPath $jarDest)) {
    Copy-Item -LiteralPath $serverJarPath -Destination $jarDest
  }

  $eulaPath = Join-Path $dir "eula.txt"
  if (-not (Test-Path -LiteralPath $eulaPath)) {
    Write-TextFile $eulaPath @"
# By changing the setting below to TRUE you are indicating your agreement to the Minecraft EULA (https://aka.ms/MinecraftEULA).
eula=false
"@
  }

  $propsPath = Join-Path $dir "server.properties"
  if (-not (Test-Path -LiteralPath $propsPath)) {
    Write-TextFile $propsPath @"
# Minecraft server properties - $Version
# Generated by setup-servers-vanilla.ps1
generator-settings=
op-permission-level=4
allow-nether=true
level-name=$($s.Level)
enable-query=false
allow-flight=false
server-port=$($s.Port)
level-type=minecraft\:normal
enable-rcon=false
force-gamemode=true
gamemode=survival
server-ip=
max-build-height=384
spawn-npcs=true
white-list=false
spawn-animals=true
hardcore=false
snooper-enabled=true
online-mode=true
resource-pack=
pvp=true
difficulty=normal
enable-command-block=false
player-idle-timeout=0
max-players=20
spawn-monsters=true
view-distance=10
generate-structures=true
motd=$($s.Motd)
"@
  }

  $startPath = Join-Path $dir "start.ps1"
  if (-not (Test-Path -LiteralPath $startPath)) {
    Write-TextFile $startPath @'
param(
  [string]$Xms = "1G",
  [string]$Xmx = "2G"
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

# Vanilla 1.21.x requires Java 21; use system java
$java = "java"

if (-not (Test-Path -LiteralPath ".\eula.txt")) {
  throw "eula.txt not found. Run setup-servers-vanilla.ps1 first."
}

$eula = Get-Content -LiteralPath ".\eula.txt" -ErrorAction Stop
if ($eula -notcontains "eula=true") {
  throw "You must accept the EULA: open .\eula.txt and set eula=true"
}

if (-not (Test-Path -LiteralPath ".\server.jar")) {
  throw "server.jar not found. Run setup-servers-vanilla.ps1 first."
}

Write-Host ("Starting vanilla server (server.jar)  RAM: Xms={0} Xmx={1}" -f $Xms, $Xmx)
& $java ("-Xms{0}" -f $Xms) ("-Xmx{0}" -f $Xmx) -jar server.jar nogui
'@
  }
}

Write-Host ""
Write-Host "Done. Vanilla 1.21.10 SandBox in servers\1.21.10\SandBox (port $basePort)."
Write-Host "Set eula=true in eula.txt, then run start.ps1."
Write-Host "Java 21 or newer is required."
